name: load_it
description: A collection of beautiful and customizable loading indicators for Flutter applications.
version: 0.0.1
homepage: https://github.com/YudizAndroidSunny/load_it
repository: https://github.com/YudizAndroidSunny/load_it
issue_tracker: https://github.com/YudizAndroidSunny/load_it/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

topics:
  - loading-indicator
  - loading-animation
  - loading-spinner
  - loading-progress
  - loading-status
  - loading-state
  - loading-indicator-flutter
  - loading-indicator-dart
  - loading-indicator-package
  - loading-indicator-library
  - spinner

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: